apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl-app
  labels:
    app: shorturl-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shorturl-app
  template:
    metadata:
      labels:
        app: shorturl-app
    spec:
      containers:
      - name: shorturl-app
        image: ghcr.io/dummy-roro/golang-shorten-url:0d7a087f5e1778281350e8f8e07ee31f55f497ec
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

