apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl-app
  labels:
    app: shorturl-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shorturl-app
  template:
    metadata:
      labels:
        app: shorturl-app
    spec:
      containers:
      - name: shorturl-app
        image: ghcr.io/dummy-roro/golang-shorten-url:dd51a5f050542b8b5e92283c198b7bb63c996ae2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

